apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
 name: registry-checker-webhook
webhooks:
- name: registry-checker-webhook.default.svc.cluster.local
  admissionReviewVersions:
  - "v1"
  sideEffects: "None"
  rules:
    - apiGroups: ["*"]
      apiVersions: ["*"]
      operations: ["CREATE", "UPDATE"]
      resources: ["*"]
  clientConfig:
    service:
      namespace: default
      name: registry-checker-webhook
      path: /validate
      port: 443
    caBundle: <BASE64 ENCODED CA CERTIFICATE>